name: pokepay_flutter_sdk
description: SDK for pokepay
version: 1.0.6
homepage: https://pay.pocket-change.jp/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.3"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  meta: ^1.7.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  plugin:
    platforms:
      android:
        package: jp.pokepay.pokepay_sdk
        pluginClass: PokepaySdkPlugin
      ios:
        pluginClass: PokepaySdkPlugin