name: pokepay_flutter_sdk
description: SDK for pokepay
version: 1.0.4
homepage: https://pay.pocket-change.jp/

environment:
  sdk: ">=2.8.3 <3.0.0"
  flutter: ">=1.17.3"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  logger: ^0.9.1
  intl: ^0.16.1
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  test: ^1.14.4

flutter:
  plugin:
    platforms:
      android:
        package: jp.pokepay.pokepay_sdk
        pluginClass: PokepaySdkPlugin
      ios:
        pluginClass: PokepaySdkPlugin